version: '3'
services:
  postgres_dev:
    image: "postgres:11"
    ports:
      - 5466:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kotlinmeetup
      POSTGRES_HOST_AUTH_METHOD: trust
  postgres_test:
    image: "postgres:11"
    ports:
      - 5467:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kotlinmeetup_test
      POSTGRES_HOST_AUTH_METHOD: trust